apiVersion: opa.k8smgmt.io/v3
kind: OPAPolicy
metadata:
  name: bp-security
  project: defaultproject
spec:
  constraintList:
  - name: allowed-repos-custom
  - name: block-nodeport-services-custom
  - name: https-only-custom
  - name: image-digests-custom
  excludedNamespaces:  
  - namespaces:
    - name: namespace-1
    processes:
    - '*'
  installationParams:
    auditFromCache: false
    auditInterval: 60
    auditMatchKindOnly: false
    constraintViolationsLimit: 20
    enableDeleteOperations: false
  sharing:
    enabled: true
    projects:
    - name: defaultproject
  syncObjects:
  - group: extentions
    kind: Pod
    version: v1
  version: v1