kind: ManagedNamespace
apiVersion: config.rafay.dev/v2
metadata:
  name: nvidia
  description: namespace for gpu-operator
  labels:
  annotations:
spec:
  type: RafayWizard
  resourceQuota:
  placement:
    placementType: ClusterSpecific
    clusterLabels:
    - key: rafay.dev/clusterName
      value: demo-gpu-eks