apiVersion: opa.k8smgmt.io/v3
kind: OPAPolicy
metadata:
  name: opa-gs-policy
  project: defaultproject
spec:
  constraintList:
  - name: rafay-request-limit-ratio-constraint
  - name: rafay-gatekeeper-allowedrepos-constraint
  excludedNamespaces:
  - namespaces:
    - name: namespace-1
    processes:
    - '*'
  installationParams:
    auditFromCache: false
    auditInterval: 60
    auditMatchKindOnly: false
    constraintViolationsLimit: 20
    enableDeleteOperations: false
  sharing:
    enabled: true
    projects:
    - name: defaultproject
  syncObjects:
  - group: extentions
    kind: Pod
    version: v1
  version: opa-gs-policy-version