apiVersion: infra.provisioner.rafay.dev/v2
kind: InfraProvisioner
metadata:
  name: gitops-eks-infraprovisioner
spec:
  type: Terraform
  gitRepository: gitops-eks-repo
  gitRevision: main
  directoryPath: /
  config:
    terraform:
      version: 0.15.0
      inputVars: []
      tfvarsFile: ""
      envVars:
      - key: RCTL_REST_ENDPOINT
        value: console.rafay.dev
        type: PlainText
      - key: RCTL_API_KEY
        value: <Key>
        type: SecureText
      - key: RCTL_API_SECRET
        value: <Secret>
        type: SecureText
      - key: RCTL_OPS_ENDPOINT
        value: console.rafay.dev
        type: PlainText
      - key: RCTL_PROJECT
        value: defaultproject
        type: PlainText
      - key: access_key 
        value: <Rafay Key>
        type: SecureText
      - key: secret_key
        value: <Rafay Secret>
        type: SecureText
      - key: AWS_ACCESS_KEY_ID
        value: <AWS Key>
        type: SecureText
      - key: AWS_SECRET_ACCESS_KEY
        value: <AWS Secret>
        type: SecureText
      backendconfig: null