apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: app-armor-custom
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/app-armor-custom/app-armor.yaml
    options: {}
    type: Yaml
  templateName: app-armor-custom