apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: privileged-container-custom
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/privileged-container-custom/privileged-container.yaml
    options: {}
    type: Yaml
  templateName: privileged-container-custom