kind: ManagedNamespace
apiVersion: config.rafay.dev/v2
metadata:
  name: autoscaler
  description: namespace for cluster autoscaler
  labels:
  annotations:
spec:
  type: RafayWizard
  resourceQuota:
  placement:
    placementType: ClusterSpecific
    clusterLabels:
    - key: rafay.dev/clusterName
      value: autoscaler-cluster