kind: ManagedNamespace
apiVersion: config.rafay.dev/v2
metadata:
  name: gputest
  description: namespace for gpu cronjob
  labels:
  annotations:
spec:
  type: RafayWizard
  resourceQuota:
  placement:
    placementType: ClusterSpecific
    clusterLabels:
    - key: rafay.dev/clusterName
      value: demo-gpueks