kind: ManagedNamespace
apiVersion: config.rafay.dev/v2
metadata:
  name: nginx-test
  description: namespace for test nginx workload
  labels:
  annotations:
spec:
  type: RafayWizard
  resourceQuota:
  placement:
    placementType: ClusterSpecific
    clusterLabels:
    - key: rafay.dev/clusterName
      value: autoscaler-cluster