apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Host-Networking-Ports
metadata:
  name: host-network-ports
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    hostNetwork: true
    min: 80
    max: 9000
