apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  claimRef:
    name: 1-pvc
    namespace: test
  hostPath:
    path: /var/lib/pv
