apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 2-pvc
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow
  volumeName: 1-pv
