apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-0
  labels:
    app: postgres
spec:
  storageClassName: glusterfs-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
