apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg== # echo -n "postgresadmin" | base64 -
  POSTGRES_PASSWORD: YWRtaW4xMjM= # echo -n "admin123" | base64 -

