apiVersion: constraints.gatekeeper.sh/v1beta1
kind: App-Armor
metadata:
  name: app-armor
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedProfiles:
    - runtime/default
