kind: ManagedNamespace
apiVersion: config.rafay.dev/v2
metadata:
  name: metallb-test-workload
  description: namespace for metallb test workload
  labels:
  annotations:
spec:
  type: RafayWizard
  resourceQuota:
  placement:
    placementType: ClusterSpecific
    clusterLabels:
    - key: rafay.dev/clusterName
      value: metallb-cluster